//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissedCallData
    {
        public long ID { get; set; }
        public Nullable<long> SN { get; set; }
        public string MOB_NO { get; set; }
        public string TIMESTAMP { get; set; }
        public string USERNAME { get; set; }
        public Nullable<bool> DONE { get; set; }
        public string FEEDBACK { get; set; }
        public string ASSIGNOR { get; set; }
        public Nullable<System.DateTime> ASSIGN_TIME { get; set; }
        public string LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
