//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileVerificationMst
    {
        public long Id { get; set; }
        public string MobileNo { get; set; }
        public string VerificationCode { get; set; }
        public string CurrentDate { get; set; }
        public string SessFrom { get; set; }
        public string SessTo { get; set; }
        public Nullable<bool> IsRegistered { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
    }
}
