//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineCategoryWiseTestVw
    {
        public int TestQuestionId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int TopicId { get; set; }
        public string TopicName { get; set; }
        public Nullable<int> DurationTypeId { get; set; }
        public Nullable<int> TestTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public bool IsTimeBased { get; set; }
        public int Test_TestQuestionMapId { get; set; }
        public Nullable<int> QuestionPatternId { get; set; }
        public string Question { get; set; }
        public bool QuestionStatus { get; set; }
        public bool MarkAsImportant { get; set; }
        public string TypeName { get; set; }
        public string TestCode { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> ClassMasterId { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<decimal> MaxMarks { get; set; }
        public string ImageUrl { get; set; }
        public string ExamName { get; set; }
    }
}
