//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentDetail
    {
        public int Id { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string ParentEmail { get; set; }
        public string ParentAlternativeEmail { get; set; }
        public string ParentAlternativeMobile { get; set; }
        public string ParentMobile { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> SiteId { get; set; }
    }
}
