//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolMaster
    {
        public int Id { get; set; }
        public Nullable<int> StateMasterId { get; set; }
        public Nullable<int> CityMasterId { get; set; }
        public string SchoolName { get; set; }
        public string AliasName { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
    }
}
