//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int SiteType { get; set; }
        public string Address { get; set; }
        public int CountryId { get; set; }
        public int StateProvinceId { get; set; }
        public string Url { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public int Sequence { get; set; }
        public string LogoUrl { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual StateProvince StateProvince { get; set; }
    }
}
