//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTestAnswerVw
    {
        public int Id { get; set; }
        public Nullable<int> StudentTestsId { get; set; }
        public Nullable<int> TestQuestionId { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> UserDetailsId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> StudentTestsStatus { get; set; }
        public Nullable<bool> StudentTestsDelete { get; set; }
        public string Answers { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsTopicWise { get; set; }
        public Nullable<bool> StudentTestAnswerStatus { get; set; }
        public Nullable<bool> StudentTestAnswerDeleted { get; set; }
        public Nullable<int> TopicId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> MCQAnswersId { get; set; }
        public Nullable<bool> IsSkip { get; set; }
        public Nullable<decimal> MarksObtained { get; set; }
        public Nullable<bool> IsNegative { get; set; }
        public Nullable<int> QuestionPatternId { get; set; }
        public string QuestionPatternName { get; set; }
        public Nullable<bool> IsTestChecked { get; set; }
        public Nullable<int> TestCheckedBy { get; set; }
        public string Refno { get; set; }
    }
}
