//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTest()
        {
            this.TestAnswersEvaluations = new HashSet<TestAnswersEvaluation>();
            this.TestTotalMarks = new HashSet<TestTotalMark>();
            this.UploadedQuestEvaluations = new HashSet<UploadedQuestEvaluation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> UserDetailsId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<bool> IsTestChecked { get; set; }
        public Nullable<int> TestCheckedBy { get; set; }
        public string Refno { get; set; }
        public bool IsMockTest { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestAnswersEvaluation> TestAnswersEvaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestTotalMark> TestTotalMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadedQuestEvaluation> UploadedQuestEvaluations { get; set; }
    }
}
