//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportTicket
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string EmailId { get; set; }
        public string FromUserId { get; set; }
        public string ToUserId { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string FilePath { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public Nullable<bool> IsAttachment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
    }
}
