//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FeeMaster
    {
        public int ID { get; set; }
        public Nullable<int> PROGRAM_ID { get; set; }
        public string EFFECTIVE_DATE { get; set; }
        public string PERSON { get; set; }
        public Nullable<decimal> APP_FEE { get; set; }
        public Nullable<decimal> CONSULT_FEE { get; set; }
        public bool STATUS { get; set; }
        public string LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
        public string BR_ID { get; set; }
        public decimal FIRST_INSTALLMENT { get; set; }
        public Nullable<decimal> SECOND_INSTALLMENT { get; set; }
        public Nullable<decimal> THIRD_INSTALLMENT { get; set; }
        public Nullable<decimal> RECEIPT_AMT { get; set; }
    
        public virtual tbl_ProgramMaster tbl_ProgramMaster { get; set; }
    }
}
