//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SMSConfig
    {
        public int ID { get; set; }
        public string PRO_URL { get; set; }
        public string PRO_USER { get; set; }
        public string PRO_PWD { get; set; }
        public string PRO_SID { get; set; }
        public string TR_URL { get; set; }
        public string TR_USER { get; set; }
        public string TR_PWD { get; set; }
        public string TR_SID { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
