//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserDetails
    {
        public int ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public string USER_PHOTO { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string NICK_NAME { get; set; }
        public string USER_EMAIL { get; set; }
        public string EMP_CODE { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_MOBILE { get; set; }
        public string JOIN_DATE { get; set; }
        public string LEFT_DATE { get; set; }
        public string COMMISION { get; set; }
        public string BRANCH { get; set; }
        public Nullable<int> CHART { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<int> NEWSLETTER { get; set; }
        public Nullable<int> EMAIL_SENT { get; set; }
        public string LAST_EMAIL_SENT { get; set; }
        public string SEQ_QUES { get; set; }
        public string SEQ_ANS { get; set; }
        public string LAST_PWD_RESET { get; set; }
        public Nullable<int> LOGIN_STATUS { get; set; }
        public string LAST_LOGIN { get; set; }
        public string SYS_IP { get; set; }
        public string SYS_NAME { get; set; }
        public Nullable<int> LOGIN_TYPE { get; set; }
        public string SIGNUP_DATE { get; set; }
        public string EXPIRY_DATE { get; set; }
        public string REG_TYPE { get; set; }
        public string LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
        public string BR_ID { get; set; }
        public string ORG_ID { get; set; }
    }
}
