//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmailLog
    {
        public decimal ID { get; set; }
        public string MAILINGLIST { get; set; }
        public string RECIPIENT { get; set; }
        public string SUBJECT { get; set; }
        public string MESSAGE { get; set; }
        public string TIME_STAMP { get; set; }
        public string SENT_BY { get; set; }
    }
}
