//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PostAgreementTemplate
    {
        public int ID { get; set; }
        public int CAT_ID { get; set; }
        public int DAY { get; set; }
        public string SUBJECT { get; set; }
        public string MESSAGE { get; set; }
    }
}
