//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SMTPConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SMTPConfig()
        {
            this.tbl_MailingList = new HashSet<tbl_MailingList>();
        }
    
        public int ID { get; set; }
        public string DOMAIN { get; set; }
        public string HOST { get; set; }
        public string UID { get; set; }
        public string PWD { get; set; }
        public Nullable<int> PORT { get; set; }
        public bool HTML { get; set; }
        public bool SSL { get; set; }
        public bool IS_DEFAULT { get; set; }
        public bool ACTIVE { get; set; }
        public string BR_ID { get; set; }
        public string LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MailingList> tbl_MailingList { get; set; }
    }
}
