//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ClientCoordinators
    {
        public long ID { get; set; }
        public long CLIENT_ID { get; set; }
        public string TYPE { get; set; }
        public string COORDINATOR { get; set; }
        public string LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    
        public virtual tbl_Client tbl_Client { get; set; }
    }
}
