//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Client()
        {
            this.tbl_ClientCoordinators = new HashSet<tbl_ClientCoordinators>();
        }
    
        public long ID { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string SALUTATION { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string DOB { get; set; }
        public string PASSPORT_NO { get; set; }
        public string PASSPORT_EXPIRY { get; set; }
        public string BIRTH_COUNTRY { get; set; }
        public string RESIDENCE_COUNTRY { get; set; }
        public string CITIZEN_COUNTRY { get; set; }
        public string PREF_LANGUAGE { get; set; }
        public string DOJ { get; set; }
        public bool ASSIGNED { get; set; }
        public string CLIENT_STATUS { get; set; }
        public bool STATUS { get; set; }
        public string ADDED_BY { get; set; }
        public string LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
        public string CLIENT_CATEGORY { get; set; }
        public string SOURCE { get; set; }
        public string CLOSING { get; set; }
        public string ASSIGNED_TO { get; set; }
        public string BR_ID { get; set; }
    
        public virtual tbl_ClientCategory tbl_ClientCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ClientCoordinators> tbl_ClientCoordinators { get; set; }
    }
}
