//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmailTemplates
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string SUBJECT { get; set; }
        public string BODY { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
        public string BR_ID { get; set; }
    }
}
