//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DefaultMailer
    {
        public int ID { get; set; }
        public string CATEGORY { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string DOMAIN { get; set; }
        public string LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
