//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PromoCode
    {
        public int Id { get; set; }
        public string PROMO_CODE { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public string APPLIED_FOR { get; set; }
        public string PROMO_DISCOUNT { get; set; }
        public bool STATUS { get; set; }
    }
}
