//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InvoiceDetails
    {
        public int ID { get; set; }
        public string DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string DUE_DATE { get; set; }
        public string PAY_MODE { get; set; }
        public string TRANS_ID { get; set; }
        public bool APPROVE { get; set; }
        public string LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
        public string BR_ID { get; set; }
        public bool SEND_INVOICE { get; set; }
        public string APPROVED_BY { get; set; }
        public string APPROVE_DATE { get; set; }
        public long CLIENT_ID { get; set; }
        public int INSTALLMENT { get; set; }
        public Nullable<int> PROGRAM_ID { get; set; }
        public Nullable<bool> WELCOME { get; set; }
    }
}
