//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CommissionMaster
    {
        public int ID { get; set; }
        public int COMM_ID { get; set; }
        public string TYPE { get; set; }
        public string COMM_FROM { get; set; }
        public string COMM_TO { get; set; }
        public string AMOUNT { get; set; }
    
        public virtual tbl_CommNameMaster tbl_CommNameMaster { get; set; }
    }
}
