//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BackgroundMailTemplates
    {
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string CLIENT_STATUS { get; set; }
        public Nullable<int> CLIENT_PROGRAM { get; set; }
        public Nullable<bool> POSITIVE { get; set; }
        public Nullable<int> DAY { get; set; }
        public string DESCRIPTION { get; set; }
        public string SUBJECT { get; set; }
        public string MESSAGE { get; set; }
        public string LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
