//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAnalytic
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> StudentTestId { get; set; }
        public string TestRefNo { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<decimal> QuestionMarks { get; set; }
        public string AnsViewTime { get; set; }
        public string AnsClickTime { get; set; }
        public string Accurecy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> AnsTime { get; set; }
        public Nullable<int> QReadTime { get; set; }
        public Nullable<int> OptnReadTime { get; set; }
    }
}
