//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAnswersEvaluation
    {
        public int Id { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> StudentTestId { get; set; }
        public Nullable<int> StudentTestAnswerId { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        public Nullable<bool> IsNegative { get; set; }
        public Nullable<decimal> NegativeMarks { get; set; }
        public Nullable<decimal> MarksObtain { get; set; }
        public Nullable<decimal> MaxMarks { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedOn { get; set; }
    
        public virtual StudentTest StudentTest { get; set; }
    }
}
