//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestVw
    {
        public int Id { get; set; }
        public Nullable<int> TopicId { get; set; }
        public string TopicName { get; set; }
        public Nullable<int> DurationMinute { get; set; }
        public Nullable<int> DurationTypeId { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> TestTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public bool IsTimeBased { get; set; }
        public bool Status { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public int SiteId { get; set; }
        public int OrgId { get; set; }
    }
}
