//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestionsMockView
    {
        public Nullable<int> LevelId { get; set; }
        public string LevelName { get; set; }
        public Nullable<int> TopicId { get; set; }
        public string TopicName { get; set; }
        public Nullable<int> QuestionPatternId { get; set; }
        public string QuestionPatternName { get; set; }
        public string ExamName { get; set; }
        public string MatrixMatchName { get; set; }
        public Nullable<int> MatrixMatchId { get; set; }
        public int QuestionId { get; set; }
        public string ObjectiveTypeName { get; set; }
        public Nullable<int> AnswerTypeId { get; set; }
        public Nullable<int> YearId { get; set; }
        public int OrgId { get; set; }
        public int SiteId { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool Deleted { get; set; }
        public bool Status { get; set; }
        public bool MarkAsImportant { get; set; }
        public string Question { get; set; }
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public string TopicCode { get; set; }
    }
}
