//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestReminder
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string ReminderName { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<int> DelayMinute { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TestId { get; set; }
        public int DelayHours { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
