//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestQuestion()
        {
            this.MatchingQstnAnswers = new HashSet<MatchingQstnAnswer>();
            this.MCQAnswers = new HashSet<MCQAnswer>();
            this.RevisionTestAnswers = new HashSet<RevisionTestAnswer>();
            this.UploadedQuestEvaluations = new HashSet<UploadedQuestEvaluation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LevelId { get; set; }
        public Nullable<int> ClassMasterId { get; set; }
        public Nullable<int> TopicId { get; set; }
        public Nullable<int> QuestionPatternId { get; set; }
        public Nullable<int> AnswerTypeId { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<int> MatrixMatchId { get; set; }
        public string ExamName { get; set; }
        public string Question { get; set; }
        public Nullable<decimal> MaxMarks { get; set; }
        public Nullable<decimal> NegativeMarks { get; set; }
        public Nullable<bool> MarkAsImportant { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> OrgId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchingQstnAnswer> MatchingQstnAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCQAnswer> MCQAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevisionTestAnswer> RevisionTestAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadedQuestEvaluation> UploadedQuestEvaluations { get; set; }
    }
}
