//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicSubjectVw
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public string TopicName { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> UserDetailsId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> TopicId { get; set; }
    }
}
