//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalQuestionAnswersVw
    {
        public string Answer { get; set; }
        public Nullable<int> ClassMasterId { get; set; }
        public Nullable<int> TestId { get; set; }
        public string Question { get; set; }
        public Nullable<int> Id { get; set; }
    }
}
