//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedQuestEvaluation
    {
        public int Id { get; set; }
        public Nullable<int> StudentTestId { get; set; }
        public Nullable<int> TestId { get; set; }
        public string RefNo { get; set; }
        public Nullable<int> TestQuestionId { get; set; }
        public Nullable<decimal> MarksObtain { get; set; }
        public Nullable<decimal> MaxMarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        public Nullable<bool> IsNegative { get; set; }
    
        public virtual StudentTest StudentTest { get; set; }
        public virtual TestQuestion TestQuestion { get; set; }
    }
}
