//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetail()
        {
            this.LastMinuteRevisions = new HashSet<LastMinuteRevision>();
            this.StudentCategoryMappings = new HashSet<StudentCategoryMapping>();
            this.StudentRevisionTests = new HashSet<StudentRevisionTest>();
            this.StudentTests = new HashSet<StudentTest>();
            this.TeacherCategoryMaps = new HashSet<TeacherCategoryMap>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int UserId { get; set; }
        public string Email { get; set; }
        public string PackageType { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string Mobile { get; set; }
        public string ImageUrl { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CityMasterId { get; set; }
        public Nullable<int> SchoolMasterId { get; set; }
        public Nullable<int> ClassMasterId { get; set; }
        public string Address { get; set; }
        public string PANNo { get; set; }
        public string Qualification { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<bool> IsSetPass { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string Religion { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<long> AdharCard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LastMinuteRevision> LastMinuteRevisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCategoryMapping> StudentCategoryMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentRevisionTest> StudentRevisionTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTest> StudentTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherCategoryMap> TeacherCategoryMaps { get; set; }
    }
}
