//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DefaultMailer
    {
        public int ID { get; set; }
        public string CATEGORY { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string DOMAIN { get; set; }
        public string HOST { get; set; }
        public string UID { get; set; }
        public string PWD { get; set; }
        public Nullable<int> PORT { get; set; }
        public bool HTML { get; set; }
        public bool SSL { get; set; }
        public bool IS_DEFAULT { get; set; }
    }
}
