//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ExpenseNote
    {
        public long ID { get; set; }
        public string EXP_CODE { get; set; }
        public string EXP_CATEGORY { get; set; }
        public string DATE { get; set; }
        public string AMOUNT { get; set; }
        public string PAY_MODE { get; set; }
        public string BANK_NAME { get; set; }
        public string TRAN_NO { get; set; }
        public string REF_CLIENT { get; set; }
        public string PAID_BY { get; set; }
        public string ENT_DATE { get; set; }
        public string ENT_BY { get; set; }
        public string LAST_UPDATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string CLIENT_NAME { get; set; }
        public string Name { get; set; }
        public string PAID_TO { get; set; }
        public string REMARKS { get; set; }
        public string PAID_NAME { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string APPROVER { get; set; }
    }
}
