//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_InvoiceDetails
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public int PackageId { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string MobileNumber { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string Date { get; set; }
        public bool Status { get; set; }
    }
}
