//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MiscFee
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string FEE_NAME { get; set; }
        public string DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> CLIENT_ID { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string PAY_MODE { get; set; }
        public string MobileNumber { get; set; }
        public string TRAN_ID { get; set; }
        public bool PAID { get; set; }
        public bool APPROVED { get; set; }
        public string CREATED_BY { get; set; }
        public string CREATED { get; set; }
        public string LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
        public string APPROVER { get; set; }
    }
}
