//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Refund
    {
        public int ID { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public string DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string PAYMODE { get; set; }
        public string NOTES { get; set; }
        public string LAST_UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
        public int PackageId { get; set; }
    }
}
