//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Reference
    {
        public string Email { get; set; }
        public int ID { get; set; }
        public string REF_EMAIL { get; set; }
        public Nullable<long> REF_BY { get; set; }
        public long REF_ID { get; set; }
        public string ENT_DATE { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string PHONE { get; set; }
        public string REF_BY_NAME { get; set; }
    }
}
