//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tys361.WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserInfo
    {
        public int Id { get; set; }
        public int USER_ID { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string RoleName { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Email { get; set; }
    }
}
